### ISSUE TITLE
LoadBalancer resource created for istio-ingressgateway stranded on teardown

### ISSUE THREAD

**Issue by thefirstofthe300** [GoogleCloudPlatform/gke-istio-vpn-demo#22]
It appears that the LB created for the istio-ingressgateway is being stranded as teardown is occurring. #21 teardown [failed](https://ci.gflocks.com/job/gke-istio-vpn-demo/14/consoleFull) after validation finished.

I would suspect that this is the result of upgrading to using managed Istio.

**Comment by chrislovecnm** [comment]
This should be fixed.
